title: Andreas Avgoustis's Homepage
page-top-title: Andreas Avgoustis
top-section-bg-text: AI/ML Engineer & Researcher
home-subtitle: Andreas Avgoustis&ensp;
copyright-text: '&copy; Andreas Avgoustis 2026. All Rights Reserved.'
