title: Andreas Avgoustis's Homepage
page-top-title: Andreas Avgoustis
top-section-bg-text: AI/ML Engineer & Researcher
home-subtitle: User Name&ensp;|&ensp;姓名
copyright-text: '&copy; Andreas Avgoustis 2026. All Rights Reserved.'
