title: Andreas Avgoustis | AI/ML Researcher

top-section-bg-text: "AI/ML Engineer & Researcher
home-subtitle: "Andreas Avgoustis"
copyright-text: "&copy; 2026 Andreas Avgoustis &middot; All rights reserved"
